import React from 'react'
import { useThemeContext } from '../../providers/useThemeContext'
import FirstFarming1 from '../../assets/images/logos/tutorial/first-farming1.png'
import FirstFarming2 from '../../assets/images/logos/tutorial/first-farming2.png'
import FirstFarming3 from '../../assets/images/logos/tutorial/first-farming3.png'
import Convert1 from '../../assets/images/logos/tutorial/convert1.jpg'
import Convert2 from '../../assets/images/logos/tutorial/convert2.jpg'
import Convert3 from '../../assets/images/logos/tutorial/convert3.jpg'
import Convert4 from '../../assets/images/logos/tutorial/convert4.jpg'
import Convert5 from '../../assets/images/logos/tutorial/convert5.jpg'
import Convert6 from '../../assets/images/logos/tutorial/convert6.png'

import {
  Container,
  TopSection,
  TopContainer,
  Inner,
  WrapperDiv,
  Title,
  DescText,
  DescImg,
  HeaderTitle,
  HeaderDesc,
  CoinSection,
} from './style'

const Home = () => {
  const { pageBackColor, fontColor } = useThemeContext()

  return (
    <Container pageBackColor={pageBackColor} fontColor={fontColor}>
      <TopSection>
        <TopContainer>
          <HeaderTitle>Your First Steps as a Crypto Farmer</HeaderTitle>
          <HeaderDesc>Learn how to get started with Harvest.</HeaderDesc>
        </TopContainer>
      </TopSection>
      <Inner>
        <CoinSection>
          <WrapperDiv>
            <DescText>In this tutorial, you will learn the following:</DescText>
            <br />
            <DescText>
              <ul className="top-list">
                <li>How can you benefit with yield farming</li>
                <li>The tools you need to use Harvest</li>
                <li>How to convert your ETH or USDC into a productive asset</li>
                <li>How to understand your yield earnings</li>
              </ul>
            </DescText>
          </WrapperDiv>
          <WrapperDiv>
            <Title>Introduction - What is Yield Farming?</Title>
            <DescText>
              Before we begin, let us briefly recap what yield farming essentially is.
              <br />
              <br />
              Yield farming involves engaging your cryptocurrency in activities like lending,
              providing liquidity, or staking, enabling you to earn fees and token rewards from
              various projects.
              <br />
              <br />
              Harvest&apos;s farms make it easier and more efficient to earn on your crypto from a
              single and intuitive dashboard, compared to managing everything on your own.
            </DescText>
          </WrapperDiv>
          <WrapperDiv>
            <Title>Benefits of Yield Farming with Harvest</Title>
            <DescText>
              The key advantage is our auto-compounding feature, where the fees generated by your
              crypto are automatically reinvested, leading to higher yields and lower network fees,
              which are collectively shared among Harvest&apos;s users.
              <br />
              <br />
              Moreover, Harvest&apos;s expert contributors have been dedicatedly researching and
              crafting high-yield strategies since 2020, ensuring that you have access to
              cutting-edge opportunities.
            </DescText>
          </WrapperDiv>
          <WrapperDiv>
            <Title>What do I need to get started?</Title>
            <DescText>
              To get started with yield farming, you need two things:
              <br />
              <br />
              1. A non-custodial wallet such as{' '}
              <a href="/#" target="_blank" rel="noopener noreferrer">
                MetaMask
              </a>
              {', '}
              <a href="/#" target="_blank" rel="noopener noreferrer">
                Rabby
              </a>{' '}
              or{' '}
              <a href="/#" target="_blank" rel="noopener noreferrer">
                Coinbase Wallet
              </a>{' '}
              - either a desktop browser extension or a mobile app.
              <br />
              2. Some crypto - as low as $5 in USDC or ETH is enough to get your feet wet!
              <br />
              <br />
              <span>
                We highly recommend Coinbase Wallet, as it will be the easiest one to start with
                Harvest&apos;s Beginners section.
              </span>
              <br />
              <br />
              Learn how to Transfer crypto from your Coinbase account to your Coinbase Wallet with{' '}
              <a href="/#" target="_blank" rel="noopener noreferrer">
                this tutorial
              </a>
              .
              <br />
              <br />
              If you have funds on a crypto exchange like Binance or Kraken and don&apos;t know how
              to transfer them to another non-custodial wallet than Coinbase Wallet, please look for
              help on the support page of your wallet provider.
            </DescText>
          </WrapperDiv>
          <WrapperDiv>
            <Title>Your first farming experience</Title>
            <DescText>
              Harvest prepared a special section called For Beginners, where you can start yield
              farming in just a few clicks.
              <br />
              <br />
              Open{' '}
              <a
                href="https://app.harvest.finance/beginners"
                target="_blank"
                rel="noopener noreferrer"
              >
                app.harvest.finance/beginners
              </a>{' '}
              to see the following section. Here, you will see two farms to start with - USDC & ETH
              farms.
            </DescText>
            <DescImg src={FirstFarming1} alt="tutor" />
            <DescText>
              Before you enter, we display each farm&apos;s APY and the network it operates on. All
              Beginner farms are built on Coinbase&apos;s Base Network.
              <br />
              <br />
              Which one should you choose?
              <br />
              <br />
              In the USDC farm, your yield is basically in US dollars. This farm earns you more
              USDC. If you don&apos;t like volatility and are just looking for a nice way to earn
              more USDC, this one is for you.
              <br />
              <br />
              In the ETH farm, the value of your earnings denominated in USD can change because of
              market prices, much like holding ETH directly. But, you earn and gather more ETH in
              this farm. If you are an ETH bull, this one is for you.
              <br />
              <br />
              The next part of the tutorial will help you get started with the ETH farm. Don&apos;t
              worry; getting started with USDC Farm would be no different.
              <br />
              <br />
              Upon opening the ETH farm, you will be presented with the following view:
              <br />
              <br />
            </DescText>
            <DescImg src={FirstFarming2} alt="tutor" />
            <DescText>
              To start to yield farming via ETH farm, you will need to convert your ETH into
              Harvest&apos;s interest-bearing token, called a fToken. It&apos;s a token that
              entitles you to initially converted ETH and the yield it accrues.
              <br />
              <br />
              Each farm has its unique fToken. The beginner&apos;s ETH farm is called fETH.
              <br />
              <br />
              Converting your ETH into fETH can be done via the module highlighted in blue below:
              <br />
              <br />
            </DescText>
            <DescImg src={FirstFarming3} alt="tutor" />
          </WrapperDiv>
          <WrapperDiv>
            <Title>Using the Convert module</Title>
            <DescText>
              To continue, you need &gt;$5 of ETH or USDC on your non-custodial wallet and be
              connected to the Base Network.
              <br />
              <br />
              Ready? Let&apos;s get started.
              <br />
              <br />
              First, connect your wallet to Harvest via the [Connect Wallet] button in the top-left
              corner.
            </DescText>
            <DescImg src={Convert1} alt="tutor" />
            <DescText>
              Ensure that your wallet&apos;s selected network is Base. Harvest app should display
              the Base icon next to your address alongside the [Connected] status.
              <br />
              <br />
              Once connected, head over to the Convert module. Its default state will have ETH
              pre-selected as the input token, while the Balance Available is where the UI will
              display the number of ETH it reads from your connected wallet.
            </DescText>
            <DescImg src={Convert2} alt="tutor" />
            <DescText>
              To get a sense of potential yield on your ETH, enter any amount and give it a few
              seconds to calculate Estimated Monthly and Daily Yield.
            </DescText>
            <DescImg src={Convert3} alt="tutor" />
            <DescText>
              In our case, 1 ETH turned into fETH should give us an average of $7.51 in monthly and
              $0.246 in daily yield. A reminder that these are estimates subject to change as the
              USD pricing of ETH fluctuates.
              <br />
              <br />
              Tip: You can get started with smaller amounts like 0.01 ETH as well.
              <br />
              <br />
              Next, click on [Preview & Earn Yield] to be presented with a summary and a progress
              bar on a pop-up in the middle of your screen.
            </DescText>
            <DescImg src={Convert4} alt="tutor" />
            <DescText>
              Here, you can check on the amount of ETH you entered to convert and the number of
              fTokens, in this case, fETH, that you will receive in return.
              <br />
              <br />
              Reminder: fETH is your receipt entitling you to initially converted funds plus its
              accrued yield.
              <br />
              <br />
              To convert your ETH into fETH, you must first go through two steps: Approve Token &
              Confirm Transaction. To fulfill each, your wallet will prompt you to confirm the
              action and pay a network fee (usually a few cents on Base Network).
              <br />
              <br />
              The interactive progress bar will keep you informed of what step you&apos;re currently
              at.
              <br />
              <br />
              If you encounter any problems during this process, reach out for help on
              Harvest&apos;s Discord channel.
            </DescText>
            <DescImg src={Convert5} alt="tutor" />
            <DescText>
              After confirming the transaction, the progress bar will turn fully green and ask you
              to close this pop-up window. Do so and return to your panel to see your yield farming
              position in full glance:
            </DescText>
            <DescImg src={Convert6} alt="tutor" />
            <DescText>
              Let&apos;s recap all the essential metrics to track your yield properly:
            </DescText>
            <br />
            <br />
            <DescText>
              <ul>
                <li>
                  <span>My Balance box</span> informs you about the USD value of your fETH
                </li>
                <li>
                  <span>Monthly Yield & Daily Yield boxes</span> provide an estimated yield of your
                  fETH denominated in USD. Note it&apos;s subject to frequent changes as ETH&apos;s
                  price fluctuates.
                </li>
                <li>
                  On the right side, you will see a <span>box with a breakdown</span> of your total
                  fETH holdings and Underlying Balance, a number that auto-compounds and reflects
                  the present state of your yield in this farm denominated in ETH. By design,
                  Underlying Balance should only increase over time.
                </li>
                <li>
                  The <span>My Balance chart</span> lets you preview your earnings in USD and
                  Underlying Token realms. Remember, it might take up to 48 hours for the chart to
                  display the first history data points.
                </li>
              </ul>
            </DescText>
            <DescText>
              <span>Tips:</span>
            </DescText>
            <DescText>
              <ul>
                <li>You can convert more ETH into fETH at any time</li>
                <li>You can revert fETH into ETH at any time</li>
              </ul>
            </DescText>
            <DescText>
              That&apos;s it! You are now a crypto farmer, earning yield on your ETH.
            </DescText>
            <DescText>
              If you have any problems with this tutorial, don&apos;t hesitate to get in touch with
              us on Discord.
            </DescText>
          </WrapperDiv>
        </CoinSection>
      </Inner>
    </Container>
  )
}

export default Home
